default: &default
  adapter: postgresql
  encoding: unicode
  database: qualidade_software_db
  pool: 5
  username: luiz
  password:

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
